
ALTER USER 'admin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
FLUSH PRIVILEGES;
/* CREATE MEDICAL SHOP DB */

create database MEDICAL_SHOP;

USE MEDICAL_SHOP;

/* CREATE CATEGORY TABLE */

CREATE TABLE CATEGORY (
    CATEGORY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

/* ALTER CATEGORY TABLE TO ADD AUTO_INCREMENT STARTING VALUE */

ALTER TABLE CATEGORY AUTO_INCREMENT = 100;

/* CREATE PRODUCT TABLE */

CREATE TABLE PRODUCT (
	PRODUCT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_USES VARCHAR(250) NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(250),
    PRODUCT_COMPANY_NAME VARCHAR(100) NOT NULL,
    PRODUCT_PRICE FLOAT NOT NULL DEFAULT 0,
    PRODUCT_DISCOUNT FLOAT NOT NULL DEFAULT 0,
    PRODUCT_LOCATION_IN_STORE VARCHAR(50) NOT NULL,
    DATE_OF_VALIDITY VARCHAR(50)
);
ALTER TABLE PRODUCT ADD COLUMN PRODUCT_CATEGORY_ID INT NOT NULL; 
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);

DESCRIBE PRODUCT;

/* CREATE STOCK TABLE */
CREATE TABLE PRODUCT_STOCK (
PRODUCT_STOCK_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PRODUCT_ID INT NOT NULL UNIQUE,
PRODUCT_QUANTITY INT NOT NULL,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) 
ON DELETE CASCADE
ON UPDATE CASCADE
);

/* QUERY STOCK DETAILS */

SELECT 
A.PRODUCT_STOCK_ID,
A.PRODUCT_ID,
A.PRODUCT_QUANTITY,
B.PRODUCT_NAME,
B.PRODUCT_USES,
B.PRODUCT_DESCRIPTION,
B.PRODUCT_COMPANY_NAME,
B.PRODUCT_PRICE,
B.PRODUCT_DISCOUNT,
B.PRODUCT_LOCATION_IN_STORE,
B.DATE_OF_VALIDITY,
C.CATEGORY_ID,
C.CATEGORY_NAME
FROM PRODUCT_STOCK A, PRODUCT B, CATEGORY C
WHERE
A.PRODUCT_ID = B.PRODUCT_ID AND 
B.PRODUCT_CATEGORY_ID = C.CATEGORY_ID; 
