
ALTER USER 'admin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
FLUSH PRIVILEGES;
/* CREATE MEDICAL SHOP DB */

create database MEDICAL_SHOP;

USE MEDICAL_SHOP;

/* CREATE CATEGORY TABLE */

CREATE TABLE CATEGORY (
    CATEGORY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

/* ALTER CATEGORY TABLE TO ADD AUTO_INCREMENT STARTING VALUE */

ALTER TABLE CATEGORY AUTO_INCREMENT = 100;

/* CREATE PRODUCT TABLE */

CREATE TABLE PRODUCT (
	PRODUCT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_USES VARCHAR(250) NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(250),
    PRODUCT_COMPANY_NAME VARCHAR(100) NOT NULL,
    PRODUCT_PRICE FLOAT NOT NULL DEFAULT 0,
    PRODUCT_DISCOUNT FLOAT NOT NULL DEFAULT 0,
    PRODUCT_LOCATION_IN_STORE VARCHAR(50) NOT NULL,
    DATE_OF_VALIDITY VARCHAR(50)
);
ALTER TABLE PRODUCT ADD COLUMN PRODUCT_CATEGORY_ID INT NOT NULL; 
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);

DESCRIBE PRODUCT;

